### ISSUE TITLE
Trouble adding double issues to collection

### ISSUE THREAD

**Issue by joannabergstrom** [ducksmanager/core#1]
Time of discovery of error:
Between 21:00-22:00 (GMT+2), Saturday 8th of May 2021

What I tried:
In the list of issues on the "my collection" page , I selected a double issue, set the status to owned and then clicked save.

Description of error:
Selection did not update and the post request to add the issue to collection returned an error 500. Page does not refresh.

I tried multiple double issues (see examples below) and different combinations of issues to add. It appeared as if any time an issue with the title/name in the format "year-issue-issue" was part of the request, the request failed with an error 500.

I attempted to add the same issues in both Chrome and Firefox on PC and through What the Duck on android. All three services gave the same result and reloading page without cache made no difference.

Examples of some of the issues I tried adding were:
1999-13-14
1997-21-22
1997-51-52
1995-21-22

All issues belong to the Swedish series "Kalle Anka & co".

Throughout, issues with the "year-issue" title format could be added as long as they were not selected in combination with a double issue. Adding multiple issues with at least one double issue amongst them resulted in an error.

Adding one or multiple double issues in the same request made no difference , the same error occurred regardless.

**Comment by bperel** [comment]
Thank you @joannabergstrom . The issue is fixed now :-)
