### ISSUE TITLE
Inducks offline?

### ISSUE THREAD

**Issue by Drudoo** [ducksmanager/core#11]
Hey! 

With inducks seemingly offline, what are the options for hosting this? 

It seems the last isv on archive.org is from 2021, so one could use that as basis for running your stack. Do you have a newer isv available locally?

**Comment by bperel** [comment]
Hi,
I can re-create the ISVs from the DucksManager database, where the ISVs were imported successfully for the last time on July 16th. Would that be of interest to you?

**Comment by Drudoo** [comment]
That would be amazing. Thank you! I’m gonna spin up DucksManager as a replacement and get starting tracking my collection there.

**Comment by bperel** [comment]
Alright, I'll create a dump this evening or tomorrow. But you're aware that you can just go to ducksmanager.net to manage your collection, right? No need to spin it up locally.

**Comment by Drudoo** [comment]
That would be great! No rush. I like to keep a local backup to play around with.
Honestly had no idea. I'll sign up there and see how it is.

**Comment by bperel** [comment]
Here is the dump: https://mega.nz/file/RfBlTQpY#QIw39U5-pFfOFriIKto2iWuM2fidWLT8EfwAg9Fj-4M

**Comment by bperel** [comment]
And if you're interested in spinning up a database using these ISVs, you may be interested in [coa-updater](https://github.com/bperel/coa-updater) :-)

**Comment by Drudoo** [comment]
Thanks i grabbed a copy of the file! I'll take a look at that :) 

If Inducks stays offline, would you add update / insert functionality to Ducksmanager? There's covers and info missing on issues here and there.

**Comment by bperel** [comment]
Probably not: DucksManager is designed to be a website that uses the Inducks database to provide tools for Disney magazine collectors. Maintaining a clone of Inducks would be too much work. Hopefully Inducks will come back to life soon.
