### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [ducksmanager/core#154]
You probably want GPLv3-_or-later_ instead of _-only_.
for
https://hosted.weblate.org/settings/ducksmanager/dumili/
https://hosted.weblate.org/settings/ducksmanager/whattheduck/
https://hosted.weblate.org/settings/ducksmanager/glossary/

like the other components in https://hosted.weblate.org/projects/ducksmanager/#information

Specifying "_only_" creates incompatibilities and scenarios negotiating with each translator to undo it.

**Comment by bperel** [comment]
Thanks, fixed!
